version: '3'
services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
    command: npm run watch
    volumes:
      - .:/src/app
      - ./node_modules:/src/app/node_modules
    links:
      - db
    depends_on:
      - db
    ports:
      - '4000:4000'
volumes:
  data:
    driver: local
